import { z } from "zod";

export const langCodeISO6393 = z.enum([
  "eng",
  "cmn",
  "cmn-Hant",
  "yue",
  "lzh",
  "spa",
  "rus",
  "arb",
  "ben",
  "hin",
  "por",
  "ind",
  "jpn",
  "fra",
  "deu",
  "jav",
  "kor",
  "tel",
  "vie",
  "mar",
  "ita",
  "tam",
  "tur",
  "urd",
  "guj",
  "pol",
  "ukr",
  "kan",
  "mai",
  "mal",
  "pes",
  "mya",
  "swh",
  "sun",
  "ron",
  "pan",
  "bho",
  "amh",
  "hau",
  "fuv",
  "bos",
  "hrv",
  "nld",
  "srp",
  "tha",
  "ckb",
  "yor",
  "uzn",
  "zlm",
  "ibo",
  "npi",
  "ceb",
  "skr",
  "tgl",
  "hun",
  "azj",
  "sin",
  "koi",
  "ell",
  "ces",
  "mag",
  "run",
  "bel",
  "plt",
  "qug",
  "mad",
  "nya",
  "zyb",
  "pbu",
  "kin",
  "zul",
  "bul",
  "swe",
  "lin",
  "som",
  "hms",
  "hnj",
  "ilo",
  "kaz",
]);

export type LangCodeISO6393 = z.infer<typeof langCodeISO6393>;

export const langCodeToEnglishName: Record<LangCodeISO6393, string> = {
  eng: "English",
  cmn: "Simplified Mandarin Chinese",
  "cmn-Hant": "Traditional Mandarin Chinese",
  yue: "Cantonese", // not supported by franc-min
  lzh: "Literary Chinese", // not supported by franc-min
  spa: "Spanish",
  rus: "Russian",
  arb: "Standard Arabic",
  ben: "Bengali",
  hin: "Hindi",
  por: "Portuguese",
  ind: "Indonesian",
  jpn: "Japanese",
  fra: "French",
  deu: "German",
  jav: "Javanese (Javanese)",
  kor: "Korean",
  tel: "Telugu",
  vie: "Vietnamese",
  mar: "Marathi",
  ita: "Italian",
  tam: "Tamil",
  tur: "Turkish",
  urd: "Urdu",
  guj: "Gujarati",
  pol: "Polish",
  ukr: "Ukrainian",
  kan: "Kannada",
  mai: "Maithili",
  mal: "Malayalam",
  pes: "Iranian Persian",
  mya: "Burmese",
  swh: "Swahili (individual language)",
  sun: "Sundanese",
  ron: "Romanian",
  pan: "Panjabi",
  bho: "Bhojpuri",
  amh: "Amharic",
  hau: "Hausa",
  fuv: "Nigerian Fulfulde",
  bos: "Bosnian (Cyrillic)",
  hrv: "Croatian",
  nld: "Dutch",
  srp: "Serbian (Cyrillic)",
  tha: "Thai",
  ckb: "Central Kurdish",
  yor: "Yoruba",
  uzn: "Northern Uzbek (Cyrillic)",
  zlm: "Malay (individual language) (Arabic)",
  ibo: "Igbo",
  npi: "Nepali (individual language)",
  ceb: "Cebuano",
  skr: "Saraiki",
  tgl: "Tagalog",
  hun: "Hungarian",
  azj: "North Azerbaijani (Cyrillic)",
  sin: "Sinhala",
  koi: "Komi-Permyak",
  ell: "Modern Greek (1453-)",
  ces: "Czech",
  mag: "Magahi",
  run: "Rundi",
  bel: "Belarusian",
  plt: "Plateau Malagasy",
  qug: "Chimborazo Highland Quichua",
  mad: "Madurese",
  nya: "Nyanja",
  zyb: "Yongbei Zhuang",
  pbu: "Northern Pashto",
  kin: "Kinyarwanda",
  zul: "Zulu",
  bul: "Bulgarian",
  swe: "Swedish",
  lin: "Lingala",
  som: "Somali",
  hms: "Southern Qiandong Miao",
  hnj: "Hmong Njua",
  ilo: "Iloko",
  kaz: "Kazakh",
};
